version: "3.1"
services:
  sub:
    container_name: fast-sns
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: fast_sns
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "8332:3306"
    restart: always
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
